# Generated by Django 5.2.5 on 2025-08-31 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0004_place_latitude_place_longitude_place_user_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="place",
        ),
        migrations.AddField(
            model_name="photo",
            name="pending_place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="places.pendingplace",
            ),
        ),
    ]
