# Generated by Django 5.2.5 on 2025-09-01 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0005_remove_photo_place_photo_pending_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="places.place",
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="pending_place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pending_photos",
                to="places.pendingplace",
            ),
        ),
    ]
