# Generated by Django 5.2.5 on 2025-09-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0008_category_pendingplace_category_place_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="cover_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="category_covers/"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
