# Generated by Django 5.2.5 on 2025-09-23 16:50

import places.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0009_category_cover_photo_category_view_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="cover_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=places.storages.PublicMediaStorage(),
                upload_to="category_covers/",
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(
                storage=places.storages.PublicMediaStorage(), upload_to="place_photos/"
            ),
        ),
    ]
