runtime: python312

handlers:
- url: /static
  static_dir: static_collected/
- url: /.*
  script: auto
  secure: always

entrypoint: bash -c "python manage.py migrate && gunicorn -b :$PORT config.wsgi:application"

env_variables:
  DEBUG: "False"
  SECRET_KEY: "5tpqpk#1tj%#t0&8i@==ej83n(3k4oz*3!y*h-8y+ua-ui-xni"
  GCP_PROJECT_ID: "sport-places-472310"

  # --- Database Settings ---
  INSTANCE_CONNECTION_NAME: "sport-places-472310:europe-west1:sport-places-db"
  DB_NAME: "YOUR_DATABASE_NAME"
  DB_USER: "YOUR_DATABASE_USER"
  DB_PASS: "YOUR_DATABASE_PASSWORD"

  # --- Google Cloud Storage Settings ---
  GS_BUCKET_NAME: "YOUR_GCS_BUCKET_NAME"

beta_settings:
  cloud_sql_instances: "sport-places-472310:europe-west1:sport-places-db"
