"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv  # если хочешь подхватывать .env локально


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Загружаем .env (только локально; на GCP не мешает)
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', '1765362')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'


ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '.appspot.com').split(',')
# ALLOWED_HOSTS = ['127.0.0.1','localhost','0.0.0.0']

# For media files storage on GCP
GS_BUCKET_NAME = os.getenv("GS_BUCKET_NAME", "sport-places-media")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework',
    'drf_yasg',
    'drf_spectacular',
    'places',
    'storages',       # <— обязательно для работы с GCS
    'corsheaders',
]

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ]
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Sport Places API',
    'DESCRIPTION': 'API for the Sport Places catalog project',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                'places.context_processors.categories_processor',
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


import dj_database_url

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
     'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'sport_places_gpt_db'),
        'USER': os.getenv('DB_USER', 'sport_user_gpt'),
        'PASSWORD': os.getenv('DB_PASSWORD', '1765362Kavaliou#'),
        'HOST': os.getenv('DB_HOST', '/cloudsql/sport-places-472310:europe-west1:sport-places-db'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'places/static',
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Перенаправление на страницу после регистрации
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

CORS_ALLOWED_ORIGINS = [
    "https://andrei-kv.github.io",  # ваш фронтенд
]

# Настройки для медиа-файлов (загружаемые пользователями)


if os.getenv("DEBUG", "False").lower() == "true":
    # 🔹 Локальная разработка: сохраняем файлы на диск
    DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
else:
     # 🔹 Продакшен (App Engine): сохраняем файлы в Google Cloud Storage
    DEFAULT_FILE_STORAGE = "storages.backends.gcloud.GoogleCloudStorage"
    
    # Конфигурация для django-storages
    # Это имя должно совпадать с именем вашего бакета в Google Cloud Storage
    # Оно берется из переменной окружения GS_BUCKET_NAME в app.yaml
    bucket_name = os.getenv("GS_BUCKET_NAME")
    GS_BUCKET_NAME = bucket_name
    GS_DEFAULT_ACL = "publicRead"  # Новые файлы будут публично доступны для чтения
    
    MEDIA_URL = f"https://storage.googleapis.com/{bucket_name}/"


import logging
logger = logging.getLogger(__name__)
logger.warning(f"DEBUG={DEBUG}, DEFAULT_FILE_STORAGE={DEFAULT_FILE_STORAGE}, GS_BUCKET_NAME={GS_BUCKET_NAME}")


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'ERROR',
    },
}
